{% set name = "avro" %}
{% set version = "1.11.3" %}
{% set hash = "bcd838a5456b16b5b506fe9a630f0eb3f555ff0f" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/avro-{{ version }}.tar.gz
    sha1: {{ hash }}

build:
  skip: true  # [py2k]
  entry_points:
    - avro = avro.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - typing-extensions  # [py<38]

test:
  imports:
    - avro
  commands:
    - pip check
    - avro --help
  requires:
    - pip

about:
  home: https://avro.apache.org
  license: Apache 2.0
  license_file:
    - avro/LICENSE
    - avro/NOTICE
  summary: Avro is a serialization and RPC framework.
  description: |
    Apache Avro™ is a data serialization system.
    Avro provides:
    * Rich data structures.
    * A compact, fast, binary data format.
    * A container file, to store persistent data.
    * Remote procedure call (RPC).
    * Simple integration with dynamic languages. Code generation is not required to read or write data files nor to use
      or implement RPC protocols. Code generation as an optional optimization, only worth implementing for statically
      typed languages.
  license_family: Apache
  doc_url: https://avro.apache.org/docs/
  dev_url: https://github.com/apache/avro


extra:
  recipe-maintainers:
    - mariusvniekerk
