travis:
  secure:
    BINSTAR_TOKEN: Crz22V+vNrd5g93sF0k8RP1PIUCyP1jLZmgvieGH7j0DVKDxzXsPREM9KSjc1t/vBpouJrLGiPWOo0RMgKivVpLqqnOaTnzSriwo1gt2FrBYxHh6v+kyYhsNaRBLJ06bHu/HYBlCtF4RC36nawa/CV+019jgAzEVawEHfCEi5LvCHQFd7CijFRlVBSTeI2V0Ceo9eRKW1Tzc5pRD6PuqhoaQENFOXfhcM9CruVkCbHwl7ymOMJ3xEbzHQtciWnXxdRcKEsJKY738r8LvGvhPcNEjZB76KvxOoHD4dmjPguBmeGQg02tiri/+8SxeIU/9rZQfEh2G+OK2C2N2a6uLAtdTOiG426n8k/CLz3AD0y15Uu7Rf9qphb+tu8yl9+zzM6YvT7IlH6ClQQvrhVwSbw1yK/w0J7RxyjxCK7Q9Sd1sQKT7SyYpCRYDFqJozitrPk4C4ht3Jeid4IwJeQZI8dCzhJDxHDgkZwJDoqGOy8L32pyoaepV1Ju3YvPhvoXiKMsuEeIlJb7O3LK7Yt9Ls+3Zw16prgU7b2IdWP4haZoXpJIJPaZ7cs6k2SWU7vWsR/DUnl4MAQQaE3b5QX+RHRRroV2nGp5ENwFM/CLopPqMf+cmz96C1Brler773x60jLlbbe3nhc1AT4oct+sex+T+gFz4kLuQ+ce1uBXp6QM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
